dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - g++-7
      - gcc-7
      - clang-6.0
      - libboost-all-dev

matrix:
  include:
    - name: "release"
      compiler: gcc
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release"

    - name: "gnu coverage"
      compiler: gcc
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - GCOV=gcov-7
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Coverage"
      install:
        - pip install --user urllib3[secure] cpp-coveralls
      after_success:
        - which ${GCOV}
        - coveralls --gcov $(which ${GCOV}) --include crf --gcov-options '\-lmpcu' --root .. --build-root .

    - name: "gnu debug"
      compiler: gcc
      env:
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug"

    - name: "llvm debug"
      compiler: clang
      env:
        - CC_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug"

    - name: "llvm asan"
      compiler: clang
      env:
        - CC_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DASAN=1"
        - SANITIZER_CHECK=./asan-check

    - name: "llvm tsan"
      compiler: clang
      env:
        - CC_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
        - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DTSAN=1"
        - SANITIZER_CHECK=./tsan-check

before_install:
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - pushd $(pwd)
  - cd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - popd

before_script:
  - mkdir build && cd build
  - ${CC} --version
  - ${CXX} --version
  - cmake ${CMAKE_FLAGS} ../

script:
  - CTEST_OUTPUT_ON_FAILURE=TRUE make all test && ${SANITIZER_CHECK}
